name: 24_DP_MedAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.2
  - ipython=8.21.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.12
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.2
  - setuptools=69.0.3
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - astroid==3.1.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - beautifulsoup4==4.12.3
    - bert-score==0.3.13
    - cbor==1.0.0
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cwl-eval==1.0.12
    - cycler==0.12.1
    - datasets==2.14.5
    - debugpy==1.8.1
    - dill==0.3.7
    - faiss-cpu==1.8.0
    - filelock==3.13.1
    - fonttools==4.48.1
    - frozenlist==1.4.1
    - fsspec==2023.6.0
    - fst-pso==1.8.1
    - fuzzytm==2.0.5
    - gensim==4.3.0
    - huggingface-hub==0.23.0
    - idna==3.6
    - ijson==3.2.3
    - inscriptis==2.4.0.1
    - ir-datasets==0.5.5
    - ir-measures==0.3.3
    - isort==5.13.2
    - jinja2==3.1.4
    - joblib==1.3.2
    - jproperties==2.1.1
    - jupyter-core==5.7.1
    - kiwisolver==1.4.5
    - lxml==5.1.0
    - lz4==4.3.3
    - markupsafe==2.1.5
    - matplotlib==3.5.1
    - mccabe==0.7.0
    - miniful==0.0.6
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.15
    - mypy==1.9.0
    - mypy-extensions==1.0.0
    - networkx==3.3
    - nltk==3.8.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - pandarallel==1.6.5
    - pandas==2.2.0
    - pillow==10.2.0
    - psutil==5.9.8
    - pyarrow==15.0.0
    - pyautocorpus==0.1.12
    - pyfume==0.2.25
    - pylint==3.1.0
    - pyparsing==3.1.1
    - pytrec-eval-terrier==0.5.6
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - regex==2023.12.25
    - requests==2.31.0
    - rouge-score==0.1.2
    - safetensors==0.4.3
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - seaborn==0.13.2
    - sentence-transformers==2.7.0
    - simpful==2.11.1
    - smart-open==6.4.0
    - soupsieve==2.5
    - sympy==1.12
    - threadpoolctl==3.2.0
    - tokenizers==0.19.1
    - tomli==2.0.1
    - tomlkit==0.12.5
    - torch==2.3.0
    - tornado==6.3.3
    - tqdm==4.66.2
    - transformers==4.41.0
    - trec-car-tools==2.6
    - triton==2.3.0
    - tzdata==2024.1
    - unlzw3==0.2.2
    - urllib3==2.2.0
    - warc3-wet==0.2.3
    - warc3-wet-clueweb09==0.2.5
    - xxhash==3.4.1
    - yarl==1.9.4
    - zlib-state==0.1.6
